## 6-е домашнее задание - Библиотека numpy

## Якунина Е. Н., НПМбд-01-19

In [1]:
import numpy as np

1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [2]:
a = -1.3
b = 2.5
n = 64
print(np.linspace(a, b, n + 1))

[-1.3      -1.240625 -1.18125  -1.121875 -1.0625   -1.003125 -0.94375
 -0.884375 -0.825    -0.765625 -0.70625  -0.646875 -0.5875   -0.528125
 -0.46875  -0.409375 -0.35     -0.290625 -0.23125  -0.171875 -0.1125
 -0.053125  0.00625   0.065625  0.125     0.184375  0.24375   0.303125
  0.3625    0.421875  0.48125   0.540625  0.6       0.659375  0.71875
  0.778125  0.8375    0.896875  0.95625   1.015625  1.075     1.134375
  1.19375   1.253125  1.3125    1.371875  1.43125   1.490625  1.55
  1.609375  1.66875   1.728125  1.7875    1.846875  1.90625   1.965625
  2.025     2.084375  2.14375   2.203125  2.2625    2.321875  2.38125
  2.440625  2.5     ]


2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [3]:
n = int(input())
print(np.tile(np.array([1, 2, 3]), n))

5
[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


3.	Создайте массив первых 10 нечетных целых чисел.

In [4]:
print(np.array([2 * i + 1 for i in range(10)]))

[ 1  3  5  7  9 11 13 15 17 19]


4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [5]:
arr = np.zeros((10, 10))
print(np.pad(arr, 1, constant_values=1))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [6]:
arr = np.zeros((8, 8))
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [7]:
def func(i, j):
    res = i + j
    return res

n = int(input())
print(np.fromfunction(func, (n, n)))

7
[[ 0.  1.  2.  3.  4.  5.  6.]
 [ 1.  2.  3.  4.  5.  6.  7.]
 [ 2.  3.  4.  5.  6.  7.  8.]
 [ 3.  4.  5.  6.  7.  8.  9.]
 [ 4.  5.  6.  7.  8.  9. 10.]
 [ 5.  6.  7.  8.  9. 10. 11.]
 [ 6.  7.  8.  9. 10. 11. 12.]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [8]:
a = np.array([1, 2, 3])

b = np.array([[4], 
              [5], 
              [6]])

A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

B = np.array([[3, 6, -1], 
              [9, -5, -2], 
              [0, 5, -2]])

print("Перемножение вектора на вектор:", a.dot(b))
print("Перемножение матрицы на вектор:", A.dot(b), sep = "\n")
print("Перемножение матрицы на матрицу:", A.dot(B), sep = "\n")

Перемножение вектора на вектор: [32]
Перемножение матрицы на вектор:
[[ 32]
 [ 77]
 [122]]
Перемножение матрицы на матрицу:
[[ 21  11 -11]
 [ 57  29 -26]
 [ 93  47 -41]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [9]:
nums = np.arange(0, 1.05, 0.05)
arr_cos = np.cos(nums)
arr_sin = np.sin(nums)
print(np.vstack([arr_cos, arr_sin]))

[[1.         0.99875026 0.99500417 0.98877108 0.98006658 0.96891242
  0.95533649 0.93937271 0.92106099 0.9004471  0.87758256 0.85252452
  0.82533561 0.7960838  0.76484219 0.73168887 0.69670671 0.65998315
  0.62160997 0.58168309 0.54030231]
 [0.         0.04997917 0.09983342 0.14943813 0.19866933 0.24740396
  0.29552021 0.34289781 0.38941834 0.43496553 0.47942554 0.52268723
  0.56464247 0.60518641 0.64421769 0.68163876 0.71735609 0.75128041
  0.78332691 0.8134155  0.84147098]]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [10]:
a = -1
b = 3
print((b - a) * np.random.rand(3, 5) + a)

[[-0.32278054  1.12837828 -0.95691492  2.47133916  0.75597935]
 [-0.88972507  0.65003931  1.69906008  1.36238096 -0.88594135]
 [-0.5589488  -0.52705662  1.80358556  2.71391487  0.33078781]]


10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [11]:
A = np.array([[2, 7, 6.], 
              [0, -2, -1.], 
              [9, 6, 3.]])

print("Сумма всех элеметнов =", np.sum(A))
print("Сумма внутри строк =", A.sum(axis = 1))
print("Сумма внутри столбцов =", A.sum(axis = 0))
print("Среднее значение по строкам =", A.mean(axis = 1))
print("Дисперсия по строкам =", A.var(axis = 1))
print("Стандартное отклонение по строкам =", A.std(axis = 1))

Сумма всех элеметнов = 30.0
Сумма внутри строк = [15. -3. 18.]
Сумма внутри столбцов = [11. 11.  8.]
Среднее значение по строкам = [ 5. -1.  6.]
Дисперсия по строкам = [4.66666667 0.66666667 6.        ]
Стандартное отклонение по строкам = [2.1602469  0.81649658 2.44948974]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [12]:
A = np.array([[2, 7, 6.], 
              [0, -2, -1.], 
              [9, 6, 3.]])

mean_str = A.mean(axis = 1)
std_str = A.std(axis = 1)
mean_str.resize(mean_str.size, 1)
std_str.resize(std_str.size, 1)
print((A - mean_str) / std_str)

[[-1.38873015  0.9258201   0.46291005]
 [ 1.22474487 -1.22474487  0.        ]
 [ 1.22474487  0.         -1.22474487]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [13]:
A = np.array([[2, 7, 6.], 
              [0, -2, -1.], 
              [9, 6, 3.]])

print(A[A[:,2].argsort()])

[[ 0. -2. -1.]
 [ 9.  6.  3.]
 [ 2.  7.  6.]]


13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [14]:
A = np.array([[2, 7, 6.], 
              [0, -2, -1.], 
              [9, 6, 3.]])

B = A.T.dot(A)
C = A.dot(A.T)
print("Матрица B:", B, sep = "\n")
print("Матрица C:", C, sep = "\n")

Матрица B:
[[85. 68. 39.]
 [68. 89. 62.]
 [39. 62. 46.]]
Матрица C:
[[ 89. -20.  78.]
 [-20.   5. -15.]
 [ 78. -15. 126.]]


Матрицы B и C имеют размер такой же, как исходная матрица A. Их сходство заключается в том, что в них одинаковое количество строк и столбцов (элементов), они обе получаются перемножением исходной матрицы A и ее транспонированной версии. Элементы матриц B и C отличаются друг от друга, т. к. перемножаются матрица A и транспонированная матрица A в разном порядке. 

14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [15]:
print("Сумма диагональных элементов матрицы B =", np.sum(np.diag(B)))
print("Сумма диагональных элементов матрицы C =", np.sum(np.diag(C)))

Сумма диагональных элементов матрицы B = 220.0
Сумма диагональных элементов матрицы C = 220.0


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [16]:
print("Детерминант матрицы A =", np.round(np.linalg.det(A), 1))
print("Детерминант матрицы B =", np.round(np.linalg.det(B), 1))
print("Детерминант матрицы C =", np.round(np.linalg.det(C), 1)) 
print("Ранг матрицы A =", np.linalg.matrix_rank(A))
print("Ранг матрицы B =", np.linalg.matrix_rank(B))
print("Ранг матрицы C =", np.linalg.matrix_rank(C))
print("Собственные значения матрицы B =", np.linalg.eigvals(B))
print("Собственные значения матрицы C =", np.linalg.eigvals(C))

Детерминант матрицы A = 45.0
Детерминант матрицы B = 2025.0
Детерминант матрицы C = 2025.0
Ранг матрицы A = 3
Ранг матрицы B = 3
Ранг матрицы C = 3
Собственные значения матрицы B = [190.81220532  28.81955412   0.36824056]
Собственные значения матрицы C = [190.81220532  28.81955412   0.36824056]


Можно сделать вывод, что суммы диагональных элементов матриц, детерминанты, ранг матриц и собственные значения матриц B и C совпадают

16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять один из следующих с номером, сгенерированным случайным образом с помощью функции np.random.randint(10), в качестве seed для генератора случайных чисел взять номер своего студенческого билета.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        <td> 9) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        </tr>
</table>

In [17]:
np.random.seed(1032192922)
np.random.randint(10)

3

In [48]:
def f(x):
    return np.cos(np.log(x)) / x

def pryamoug(f, a, b, n):
    x = np.linspace(a, b, n + 1)
    step = x[1] - x[0]
    f_v = np.vectorize(f)
    res = f_v(x)
    return np.sum(res) * step

def trapec(f, a, b, n):
    x = np.linspace(a, b, n + 1)
    step = x[1] - x[0]
    f_v = np.vectorize(f)
    res = f_v(x)
    N = len(res) - 1
    return step / 2 * (res[0] + 2 * np.sum(res[1:N]) + res[N])

def simps(f, a, b, n):
    x = np.linspace(a, b, n + 1)
    step = x[1] - x[0]
    f_v = np.vectorize(f)
    res = f_v(x)
    N = len(res) - 1
    return step / 3 * (res[0] + 2 * np.sum(res[2: N :2]) + 4 * np.sum(res[1: N :2]) + res[N])

In [49]:
a = 1
b = np.exp(1)
n = 10
answ_pr = pryamoug(f, a, b, n)
answ_tr = trapec(f, a, b, n)
answ_sp = simps(f, a, b, n)
res = np.hstack([answ_pr, answ_tr, answ_sp])

while np.max(res) - np.min(res) >= 0.00001:
    n *= 10
    res[0] = pryamoug(f, a, b, n)
    res[1] = trapec(f, a, b, n)
    res[2] = simps(f, a, b, n)

print("Номер метода с наименьшим значением =", np.argmin(res) + 1)
print("Номер метода с наибольшим значением =", np.argmax(res) + 1)
print("Количество отрезков разбиения =", n)
print("Ширина шага =", (b - a) / n)

Номер метода с наименьшим значением = 3
Номер метода с наибольшим значением = 1
Количество отрезков разбиения = 1000000
Ширина шага = 1.7182818284590451e-06


При сравнении получаемых приближенными методами ответов между собой получилось, что наименьший ответ был получен методом Симпсона, а наибольший - методом прямоугольников. Отличие в ответах будет при 5-м знаке после запятой при шаге примерно 1,7e-06 с разбиением на 1000000 шагов

In [50]:
answer = np.tile(np.sin(1), 3)
razn = np.abs(answer - res)
print("Номер метода с наименьшим отклонением от точного ответа =", np.argmin(razn) + 1)
print("Номер метода с наибольшим отклонением от точного ответа =", np.argmax(razn) + 1)

Номер метода с наименьшим отклонением от точного ответа = 2
Номер метода с наибольшим отклонением от точного ответа = 1


При сравнении полученных приближенными методами при одинаковом количестве разбиений ответов с точным ответом получилось, что метод трапеций в данном случае дает наиболее приближенный к точному результат, в то время как метод прямоугольников - наименее близкий при одинаковом отличии между ответами в 5-м знаке после запятой.

In [51]:
answer = np.sin(1)

n_pr = 10
while np.abs(answer - pryamoug(f, 1, np.exp(1), n_pr)) >= 0.00001:
    n_pr *= 10

n_tr = 10
while np.abs(answer - trapec(f, 1, np.exp(1), n_tr)) >= 0.00001:
    n_tr *= 10

n_sp = 10
while np.abs(answer - simps(f, 1, np.exp(1), n_sp)) >= 0.00001:
    n_sp *= 10

answ_pr = pryamoug(f, a, b, n_pr)
answ_tr = trapec(f, a, b, n_tr)
answ_sp = simps(f, a, b, n_sp)
res = np.hstack([answ_pr, answ_tr, answ_sp])

print("Количество шагов в методе прямоугольников =", n_pr)
print("Количество шагов в методе трапеций =", n_tr)
print("Количество шагов в методе Симпсона =", n_sp)
print("Ответ методом прямоугольников =", res[0])
print("Ответ методом трапеций =", res[1])
print("Ответ методом Симпсона =", res[2])

answer = np.tile(np.sin(1), 3)
razn = np.abs(answer - res)
print("Номер метода с наименьшим отклонением от точного ответа =", np.argmin(razn) + 1)
print("Номер метода с наибольшим отклонением от точного ответа =", np.argmax(razn) + 1)

Количество шагов в методе прямоугольников = 1000000
Количество шагов в методе трапеций = 1000
Количество шагов в методе Симпсона = 10
Ответ методом прямоугольников = 0.8414720146773481
Ответ методом трапеций = 0.84147118483864
Ответ методом Симпсона = 0.841471515356028
Номер метода с наименьшим отклонением от точного ответа = 2
Номер метода с наибольшим отклонением от точного ответа = 1


При посчете ответов приближенными методами, сравнивая их точность сразу с точным ответом, можно сделать вывод, что заданная точность быстрее достигается методом Симпсона, а медленнее - методом прямоугольников, при этом ближе всего к ответу получается решение методом трапеций